### ISSUE TITLE
آپشن نمایش اعداد فارسی انگلیسی درست عمل نمیکند

### ISSUE THREAD

**Issue by Azoic** [majidh1/JalaliDatePicker#100]
سلام
تغییر مقدار آپشن persianDigits هیچ تغییری بوجود نمیاره، اصولا با false شدن مقدار این آپشن باید اعداد بصورت انگلیسی و با true شدن اعداد فارسی بشه، اما در هردو حالت عدد صرفا با کاراکتر فارسی نمایش میده

**Comment by majidh1** [comment]
این مورد رو تست کردم درست کار میکنه و مشکلی نداره توی دمو دیت پیکر هم این مورد بدون مشکل کار میکنه به این دلیل ایشو بسته شده است
