### ISSUE TITLE
پنجره انتخاب تاریخ در مودال بوتستراپ زیر مودال قرار می گیرید

### ISSUE THREAD

**Issue by vahidnayeri** [majidh1/JalaliDatePicker#101]
به چه صورت می توان پنجره انتخاب تاریخ را در مودال قرارداد که انتخاب زیر پنجره مودال قرار نگیرید

**Comment by majidh1** [comment]
دوست عزیز شما باید توی آپشن‌های دیتپیکر مقدار zIndex  دیت پیکر رو بالاتر از مودال بزارید
ایشو مشابه:
https://github.com/majidh1/JalaliDatePicker/issues/79
