### ISSUE TITLE
تقویم و تنظیم ساعت

### ISSUE THREAD

**Issue by persianlionn** [majidh1/JalaliDatePicker#103]
سلام وقت بخیر
بابت طراحی چنین افزونه ای از شما تشکر می کنم. امیدوارم با قدرت ادامه بدید.
سوال یک:
آیا این امکان وجود دارد که از دیت پیکر به جای تقویم استفاده کرد؟ برای مثال مانند سایت time.ir
اگر خیر آیا برنامه ای برای ایجاد چنین قابلیتی دارید؟
اگر نمونه ای می شناسید که می توان از آن برای نمایش تقویم شمسی استفاده کرد ممنون میشم معرفی کنید.
سوال دو:
آیا می شود ثانیه و دقیقه را از ساعت حذف کرد؟
باتشکر

**Comment by majidh1** [comment]
سلام وقت بخیر ممنون از مشارکت شما
برای سوال اول تا حدودی امکانش هست و در نسخه های بعدی امکانات بیشتری هم اضافه خواهد شد مهمترینش ویرایش html روز هست که با این امکان عملا میشه تغییرات زیادی در دیت پیکر داد
برای سوال دوم دقیقه رو نمیشه حذف کرد ولی برای حذف ثانیه میتوانید از کانفیگ hasSecond استفاده کنید
