### ISSUE TITLE
how to use initTime?

### ISSUE THREAD

**Issue by amirajlo** [majidh1/JalaliDatePicker#104]
سلام
سپاس بیکران  بابت ابزار ارزشمندت.
من initTime رو مقداردهی میکنم اما لحاظ نمیشه و کماکان تاریخ و زمان جاری سیستم رو لحاظ می کنه. 
ممنون میشم یک مثال بزنی که چطور کار میکنه.
من میخوام هنگامی که کاربر تقویم رو باز میکنه تاریخی که من بهش گفتم پیش فرض انتخاب شده باشه.
مرسی از وقتی که میذاری

**Comment by majidh1** [comment]
سلام ممنون از شما بابت مشارکتتون
initDate و initTime برای مقدار دهی نمایش دیتپیکر هستند در واقع دیتپیکر توی اون تاریخ و زمان باز میشه

اگه میخواهید که اینپوت مقدار اولیه بگیره لازم هست که اتریبیوت value ایننپوت رو ست کنید.

**Comment by majidh1** [comment]
بله مثلا:
```js
jalaliDatepicker.startWatch({ time: true, initTime:"01:01:01", initDate: {year:1361,month:1,day:1} });
```
