### ISSUE TITLE
امکان سویچ کاربر از تقویم شمسی به میلادی و بلعکس

### ISSUE THREAD

**Issue by parsamrz** [majidh1/JalaliDatePicker#105]
میخواستم بدونم امکان اینکه کاربر بتونه سویچ کنه بین تقویم شمسی و میلادی وجود داره ؟ بعضی وقتا کاربر تقویم میلادی رو میدونه و میخواد به میلادی وارد بکنه بتونه انتخاب کنه
![image](https://github.com/majidh1/JalaliDatePicker/assets/31309137/e0512e0e-6bb6-4e97-a43e-85e09ab3f51a)

**Comment by majidh1** [comment]
سلام این کتابخانه فقط وظیفه انتخاب تاریخ شمسی را دارد به نظرم برای این کار میتونید به صورت runtime اتریبیوت data-jdp رو حذف کنید و type=date را ست کنید که برای تاریخ میلادی از datepicker native استفاده کنید و برای شمسی از این کتابخانه
