### ISSUE TITLE
حذف زمان و کاراکتر اظافه

### ISSUE THREAD

**Issue by tahafathi2013** [majidh1/JalaliDatePicker#107]
سلام من از دیت بیکر استفاده میکنم و فقط هم تاریخ نمایش میده ولی وقتی دیتا از input یه کنترلر ارسال میشه به همراه زمان و دو کاراکتر اظافه هست میخوام فقط تاریخ رو به من بده باید چه کاری انجام بدم؟
Date = {05/08/1403 12:00:00 .}

![Ss](https://github.com/user-attachments/assets/dc93b5fa-f6eb-428c-bcd0-f1246cad8af3)

**Comment by majidh1** [comment]
سلام به نظر میرسه شما از dotnet استفاده میکنید و type مقدار را DateTime تنظیم کردید در این حالت چون type این فیلد string هست dotnet این فیلد را با مکانیزم DateTime.Parse تبدیل به Date میکنه و این مشکل پیش میاد type را به string تغییر بدین مشکل حل میشه
