### ISSUE TITLE
validate date time

### ISSUE THREAD

**Issue by faezeh1378** [majidh1/JalaliDatePicker#108]
سلام ممنون از زحماتتون
ایا این کامپوننت قابلیت اعتبار سنجی تاریخ و زمان را دارد ؟ 
ایا مقدار پیش فرضی برای داده های اشتباهی که کاربر وارد میکند دارد ؟

منظور این است که اگر کاربر یک تاریخ و یا ساعت اشتباه را دستی وارد کند calendar چه مقداری را نشان میدهد؟
چیزی که من تست کرد این است که calendar هیچ تاریخی را انتخاب نمیکند . خیلی بهتر است که تاریخ default برای این شرایط داشته باشیم
ایا من میتوانم این قابلیت به کامپوننت اضافه کنم؟

**Comment by majidh1** [comment]
سلام ممنون از شما برای مشارکت
این کتابخانه اعتبار سنجی را انجام نمیدهد و جز وظایف این کتابخانه هم اعتبار سنجی نیست. فقط موضوع مربوط به MASK Input هست که میشه به این کتابخانه اضافه نمود ولی معمولا سامانه ها یک مکانیزم MASK برای این موضوع استفاده میکنند در کنار validation اگر راهکاری برای MASK دارید که خیلی حجم کتابخانه را بالا نبرد خیلی خوشحال میشم اضافه کنید
