### ISSUE TITLE
Write Event When Change Date in Input

### ISSUE THREAD

**Issue by mehrshaddarzi** [majidh1/JalaliDatePicker#11]
Hi @majidh1 
thanks for Your Package.
I am using this date picker in WordPress Plugins.
How to write an event when change or select a day from the user in Jquery For Example:

```
jalaliDatepicker.startWatch({
    'select': function(value){
    $('#another_input').val(value);
    }
});

```

**Comment by majidh1** [comment]
Hi my friend
you can use EventListener and listen to change value input
sample: 
```javascript
	$("[data-jdp]").change(function(){
		alert($(this).val())
	})
```
or specific input sample:
```javascript
	$("#specificInputId").change(function(){
		alert($(this).val())
	})
```
or after bind inputs sample:
```javascript
	$(document.body).on("change","[data-jdp]",function(){
		alert($(this).val())
	})
```
I hope this can help you
