### ISSUE TITLE
default date not working

### ISSUE THREAD

**Issue by kamran1807** [majidh1/JalaliDatePicker#111]
the default date is not working:

jalaliDatepicker.startWatch({
          minDate: "attr",
          maxDate: "attr",
          initDate: "1380/01/01"  
        });

**Comment by majidh1** [comment]
initDate type is object
sample:

**Comment by kamran1807** [comment]
hi there, I tried this: 
// start datepicker with options
      jalaliDatepicker.startWatch({
        minDate: "attr",
        maxDate: "attr",
        initDate: { 
          year: "1380",
          month: "01",
          day: "01"
        }
     }); 
but the web page becomes unresponsive when I click on the datepicker now!

**Comment by majidh1** [comment]
change value type to number 
jalaliDatepicker.startWatch({
minDate: "attr",
maxDate: "attr",
initDate: {
year: 1380,
month: 01,
day: 01
}
});
