### ISSUE TITLE
لطفا مطالعه کنید

### ISSUE THREAD

**Issue by majidh1** [majidh1/JalaliDatePicker#12]
سلام به تمامی همکاران و دوستان عزیر

لطفا قبل از ارسال ایشو جهت پرسش لیست ایشو های بسته شده با لیبل سوال را مشاهده نمایید
[لیست سوالات](https://github.com/majidh1/JalaliDatePicker/issues?q=is%3Aissue+is%3Aclosed+label%3Aquestion)
و قبل از ارسال پیشنهاد لیست ایشوهای پیشنهادی را مشاهده نمایید
[لیست ایشوهای پیشنهاد](https://github.com/majidh1/JalaliDatePicker/issues?q=-label%3Aquestion+-label%3Abug+-label%3Adocumentation+-label%3A%22Please+Read%22)

ممنون از اینکه در پیشرفت و توسعه پروژه های متن باز همکاری میکنید.

**Comment by Absalamyar** [comment]
سلام دوست عزیز 
من میخواهم تاریخ امروز را بصورت پیش فرض در input  خود داشته باشم میشه کمک بکنین و همچنان theme  دیت پیگر را پطوری تغیر بدهم ؟
