### ISSUE TITLE
How to Add 30 Days to a Selected Date and Display Expiry Date Using JalaliDatePicker?

### ISSUE THREAD

**Issue by saboorbahawi** [majidh1/JalaliDatePicker#120]
Hello,

I'm using the [JalaliDatePicker](https://github.com/majidh1/JalaliDatePicker) for a project, and I need to implement functionality where a user selects an Issue Date (in Jalali format), and then the system automatically calculates and displays an Expire Date, which is 30 days after the Issue Date.

I have the following requirements:

The user selects an Issue Date using the Jalali date picker.
The Expire Date should be calculated as 30 days after the Issue Date.
The Expire Date should be displayed automatically in another input field.
Can you guide me on how to achieve this with JalaliDatePicker? I have already set up the JalaliDatePicker, but I need help with adding 30 days to the selected Issue Date and displaying the Expire Date.

Any help would be appreciated!

Thank you!
به فارسی هم پاسخ بدهید مشکلی نخواهم داشت ممنون

**Comment by majidh1** [comment]
hi there! You can easily achieve this by using the **moment-jalaali** library for handling Jalali date calculations

here's a simple step by step guide:

1- **listen for changes to the issue date:** use an event listener to detect when a user selects a date in the **JalaliDatePicker** input field

2- **calculate the expire date:** Add 30 days to the selected date using moment-jalaali or if you prefer, implement a custom calculation logic

3- d**isplay the expire date:** automatically update another input field with the calculated Expire Date

example:

```js
document.getElementById('issue-date').addEventListener('change', function () {
    const issueDate = this.value; // 1
    const expireDate = moment(issueDate, 'jYYYY/jMM/jDD').add(30, 'days').format('jYYYY/jMM/jDD'); //2
    document.getElementById('expire-date').value = expireDate; // 3
});

```
