### ISSUE TITLE
سلام اگه بشه به صورت پکیج لاراول در بیارید که با کامپوزر استفاده بشه خیلی خوب میشه 

### ISSUE THREAD

**Issue by farrokhPeyGhayyem** [majidh1/JalaliDatePicker#17]
با توجه به تعداد زیاد دولوپر های لاراول سلام اگه بشه به صورت پکیج لاراول در بیارید که با کامپوزر استفاده بشه خیلی خوب میشه

**Comment by mhyeganeh** [comment]
@farrokhPeyGhayyem 

دقیقا متوجه نشدم چجوری یک پکیج جاوااسکریپتی که مربوط به فرانت اند هست رو ببریم سمت لاراول و پکیج کامپوزر...؟ 🙄
چه ارتباطی اصلا بینشون وجود داره؟

مثلا می خواهید از دستورات بِلید استفاده کنید؟
 چه کاریه خوب واقعا...!؟

**Comment by boobProgrammer** [comment]
مبخواد کارش راحت بشه :))
خب 4 تا کلیک کن نصبش کن همینجوری طبق راهنما
از سازنده پکیج برای این دیت پیکر زیبا تشکر میکنم بسیار زیاد
و لطفا در صورتی که امکانش هست انتخاب زمان هم بزارید براش 
سپاس
