### ISSUE TITLE
عدم تبدیل به میلادی

### ISSUE THREAD

**Issue by farrokhPeyGhayyem** [majidh1/JalaliDatePicker#18]
سلام ممنون بابت کار قشنگتون ولی بخش تبدیل زمان از شمسی به میلادی رو نداره و نمیخوام شمسی تو دیتا بیس ثبت بشه...

**Comment by majidh1** [comment]
سلام تشکر از شما
این مورد باید سمت سرور کنترل بشه و جایی که باید دیتا تبدیل بشه عمل تبدیل را انجام دهید
اگر سمت کلاینت قرار به انجام باشه بهتره یک hiddenField داشته باشید که با تغییر تاریخ شمسی تاریخ میلادی رو محاسبه کنه و توی سرور از مقدار اون استفاده کنید.
امیدوارم این کامنت براتون مفید باشه

**Comment by habibi-dev** [comment]
ممنون از شما ولی این فیچر یه قابلیت معمول هست که نمایش اون فیلد به صورت شمسی باشه ولی در نهایت میلادی برای سرور ارسال بشه این طوری فقط اضافه کاری هست که ما باید در کنار پکیج شما بیایم و یه چیزی برای تبدیل به میلادی استفاده کنیم
