### ISSUE TITLE
نمایش تقویم در یک فرم تعبیه شده داخل مدال

### ISSUE THREAD

**Issue by hamidrezashahnazari** [majidh1/JalaliDatePicker#2]
سلام . چطور میتونم  این دیت پیکر رو داخل یک فرم که تو مدال هست باز کنم 
از کانتینر هم استفاده کردم
 اما جواب نداد

**Comment by majidh1** [comment]
سلام
دیت پیکر مشکلی برای باز شدن در مدال نداره فقط شاید زدایندکس مدال بالاتر از زدایندکس دیت پیکر باشه که با تنظیم زدایندکس مشکل برطرف میشه

یک نمونه استفاده هم داره که تصویرش رو ضمیمه کردم. (modal bootstrap)
`{
            zIndex: 1999
        }`

![dpinmodal](https://user-images.githubusercontent.com/43379900/113809411-4b99aa00-977d-11eb-9dd1-8990bcb82bd9.png)

**Comment by hamidrezashahnazari** [comment]
سلام ممنون از پاسختون
با زد ایندکس جواب داد
