### ISSUE TITLE
قابلیت استفاه در جنگو

### ISSUE THREAD

**Issue by vahidnadi** [majidh1/JalaliDatePicker#21]
درود بر شما 
امکان استفاده این تقویم در جنگو وجود داره ؟  من خیلی تلاش کردم ولی در  قالبی که مقادیر  آن از طریق فرم جنگو  پر میشود نتوانستم از آن استفاده کنم

**Comment by BamdadMeh** [comment]
ربطی نداره که ، هرجا بخای میتونی استفاده کنی
در جنگو میتونی به 
widget  
های های اون فرم اضافه کنی ، 
چه modelform  باشه
چه form  معمولی

فقط بحث اعتبار سنجی تاریخ رو باید هندل کنی وگرنه به مشکل میخوری

**Comment by vahidnadi** [comment]
شاید نتونستم منظور رو درست بیان کنم من دنبال نمونه پیاده سازی شده نحوه استفاده از  این  تقویم در جنگو هستم در برنامه خودم استفاده کردم ولی صرفا یک ورودی متنی نمایش میده

**Comment by BamdadMeh** [comment]
من خودم استفاده کردم از همین توی فرم های جنگو 
کدتو بفرستم تا بگم کجارو داری اشتباه میکنی

**Comment by vahidnadi** [comment]
فایلها بعلاوه  تغییر در پسوند جهت سهولت در ارسال خدمت شما
[forms.py.txt](https://github.com/majidh1/JalaliDatePicker/files/7741433/forms.py.txt)
[lottery.html.txt](https://github.com/majidh1/JalaliDatePicker/files/7741435/lottery.html.txt)
[views.py.txt](https://github.com/majidh1/JalaliDatePicker/files/7741436/views.py.txt)

**Comment by BamdadMeh** [comment]
این کد هارو بزار تو فایل forms.py
توی صفحه  html هم
فایل های css و js 
مربوط به  این datepicker  رو
لود کن

خبرشو بده که درست شد یا نه

`from  django  import forms
from  crispy_forms.helper import FormHelper
from  crispy_forms.layout import Layout,Submit
from  django.shortcuts import render
from  django.urls import reverse_lazy
from  .models import Drawparameters,Transaction
from django.db.models import Min
from django.db.models import Max

from django import forms
# from jalali_date.fields import JalaliDateField, SplitJalaliDateTimeField
# from jalali_date.widgets import AdminJalaliDateWidget, AdminSplitJalaliDateTime


class DateInput(forms.DateInput):
    input_type='date'
    
class  DrawparametersForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['fromdate'].widget.attrs.update({'data-jdp':''})
        self.fields['todate'].widget.attrs.update({'data-jdp':''})

    class Meta:
        model = Drawparameters
        fields = ['minscore','maxscore','chanceunit','winners','fromdate','todate']
`

**Comment by vahidnadi** [comment]
سلام مجدد
تغییراتی که زحمت کشیدید و اصلاح کردید رو اعمال کردم متاسفانه هنوز مشکل وجود داره در واقع  در قسمت  تمپلت مشکل دارم شکل ورودیها در فرم به  صورت زیر تعریف شده

                  <div id='fromdate'  class="form-group col-md-6 mb-0">
                    <script>
                      jalaliDatepicker.startWatch();
                    </script> 
                    {{ form.fromdate|as_crispy_field }}
                  </div>
                  <div id='todate' class="form-group col-md-6 mb-0">
                    {{ form.todate|as_crispy_field}}
                  </div>
حالا من نمیدونم ردبف سوم راهنما  یا همان خظ  زیر رو به چه طریق اعمال کنم 

<input data-jdp>

چون ورویها  رو از طریق فرم به صورت   زیر دریافت میکنم 

                    {{ form.todate|as_crispy_field}}

**Comment by vahidnadi** [comment]
سلام مجدد
تغییراتی که زحمت کشیدید و اصلاح کردید رو اعمال کردم متاسفانه هنوز مشکل وجود داره در واقع در قسمت تمپلت مشکل دارم شکل ورودیها در فرم به صورت زیر تعریف شده
<div>
          {{ form.fromdate|as_crispy_field }}
 </div>
<div> 
{{ form.todate|as_crispy_field}}
 </div>

حالا من نمیدونم ردبف سوم راهنما یا همان خظ زیر رو به چه طریق اعمال کنم
<input data-jdp>

اگر به صورت زیر اعمال کنم  

{{ form.todate  jdp}}

خطای زیر 

Could not parse the remainder: ' jdp' from 'form.fromdate jdp'  
 رخ میدهد .

**Comment by vahidnadi** [comment]
سلام مجدد
تغییراتی که زحمت کشیدید و اصلاح کردید رو اعمال کردم متاسفانه هنوز مشکل وجود داره در واقع در قسمت تمپلت مشکل دارم شکل ورودیها در فرم به صورت زیر تعریف شده
{{ form.fromdate|as_crispy_field }}
{{ form.todate|as_crispy_field}}

حالا من نمیدونم ردبف سوم راهنما یا همان خظ زیر رو به چه طریق اعمال کنم

<input data-jdp>

اگر به صورت زیر اعمال کنم

{{ form.todate jdp}}

خطای زیر

Could not parse the remainder: ' jdp' from 'form.fromdate jdp'
رخ میدهد .

**Comment by vahidnadi** [comment]
سلام مجدد 
با روشی که گفتید جلو رفتم ولی هنوز مشکل وجود داره در واقع  ردیف سوم راهنما که اضافه کردن یک ویژگی   به ورودی را مشخص میکند ` <input data-jdp>`
 باعث ابهام من شده است چون شکل ورودیها در قالب به صورت زیر است 

`                  <div id='fromdate'  class="form-group col-md-6 mb-0">
                    <script>
                      jalaliDatepicker.startWatch();
                    </script> 
                    {{ form.fromdate|as_crispy_field }}
                  </div>
                  <div id='todate' class="form-group col-md-6 mb-0">
                    {{ form.todate|as_crispy_field}}
                  </div>
`
و اگر به اونها 

`data-jdp` 
اضافه کنم پیام خظای زیر را می دهد 

Could not parse the remainder: '   data-jdp' from 'form.fromdate   data-jdp'

**Comment by BamdadMeh** [comment]
من فکنم بخاطر اینکه داری از 
crispy  
استفاده می کنی ،
حذفش کن ،
اگه style  هم میخوای بدی
از همین روش که من زدم استفاده کن
crispy  کلا اضافه هست
جنگو نیازی به crispy  نداره

**Comment by vahidnadi** [comment]
crispy 
 رو هم حذف کردم باز هم نشد 
نمیدونم امکانش هست یک نمونه کامل از کدی که از‌
modelform  
همراه با 
datepicker   
رو بذارید تا با کد های خودم مطابقت بدم ؟

**Comment by BamdadMeh** [comment]
سلام
این کد رو تست کن

`class  DrawparametersForm(forms.ModelForm):

    fromdate = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control','data-jdp':''}))
    todate = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control','data-jdp':''}))


    class Meta:
        model = Drawparameters
        fields = ['minscore','maxscore','chanceunit','winners']`

**Comment by vahidnadi** [comment]
نه متاسفانه 
عکسش رو ضمیمه کردم 
![err1](https://user-images.githubusercontent.com/39686676/147207556-a3f94ff1-2294-4c75-9707-af1670b2825e.png)

**Comment by BamdadMeh** [comment]
یجارو داری اشتباه میکنی
یبار دیگه از کدهای جدیدت عکس بگیر بفرست
از کدهای model  هم بفرست

**Comment by vahidnadi** [comment]
اشتباه  در ارث بری قالب پیش اومده بود  قالب والد و فرزندرا با هم ترکیب کردم مشکل حل شد  فقظ برچسب های  
fromdate , todate 
 رو نمیدونم چطور تغییر بدم ؟
![err1](https://user-images.githubusercontent.com/39686676/147234196-c60864c0-24aa-42d4-be6e-24380539472d.png)

**Comment by vahidnadi** [comment]
فقط بحث مدیریت داده ها میمونه که ظاهرا با قالب تاریخ همخوانی نداره و به نظر میرسه که باید در قالب رشته ردازش بشه 
![err1](https://user-images.githubusercontent.com/39686676/147237470-c7908e26-1480-41f4-9fed-26a5118ebf5f.png)

**Comment by BamdadMeh** [comment]
این کارایی که گفتی خیلی راحت هست
یه سرچ بزن که بتونی label  رو درست کنی
قالب تاریخ هم داکیومنت رو بخون که بتونی تغییرش بدی به راحتی

**Comment by vahidnadi** [comment]
از بابت پشتیبانی و همکاری شما خیلی ممنونم

**Comment by majidh1** [comment]
@BamdadMeh  🥇🏆
ممنون از اشتراک گذاری و همکاری با developer ها، این عملکرد قطعا باعث پیشرفت رویکرد OpenSource و مفهوم  Knowledge sharing میشه.
