### ISSUE TITLE
قابلیت اضافه نمودن چندین انپوت دیتپیکر در یک صفحه

### ISSUE THREAD

**Issue by AbdulQaharRahmani** [majidh1/JalaliDatePicker#23]
در حال حاضر اگر دو دانه input با data-jdp در یک صفحه باشد تنها value یک کدام کار میدهد.  از شما خواهش میکنم که قابلیت اضافه نمودن چندین input با data-jdp های متفاوت را اضافه نمایید.

**Comment by majidh1** [comment]
سلام ممنون ازمشارکت موردی که مطرح کردین دیده نمیشه.
این لینک نمونه استفاده از چندین input هست
https://majidh1.github.io/JalaliDatePicker

**Comment by AbdulQaharRahmani** [comment]
ممنون بابت جوابتان . مشکل از جانب خودم بود دیروز به اش پی بردم . باز هم تشکر
