### ISSUE TITLE
z-index jdp-container از انلاین استایل به کلاس تبدیل شود 

### ISSUE THREAD

**Issue by AbdulQaharRahmani** [majidh1/JalaliDatePicker#24]
زید اندیکس جدی پی کانتینر فعلاً به صورت انلاین استایل اضافه شده است و قیمتش 1000 میباشد. ما نیاز داریم که آنرا به 10,000 تبدیل کنیم ولی چون کلاس نیست نمیتوانیم اوررایت کنیم اگر لطف نمایید این را به کلاس تبدیل کنید ممنون میشویم

**Comment by majidh1** [comment]
سلام ممنون از مشارکت شما
کافیه وقتی میخواید استارت بزنید پارامتر زداینکس رو مقدار دهی کنید
مستندات پارامتر ها در گیت هاب موجود هست

jalaliDatepicker.startWatch({
     zIndex:10000
});

**Comment by AbdulQaharRahmani** [comment]
تشکر
