### ISSUE TITLE
نمایش با کلیک برروی دکمه

### ISSUE THREAD

**Issue by RmzDav** [majidh1/JalaliDatePicker#25]
چگونه می تونم تاریخ را با زذن یک دکمه باز کنم

**Comment by majidh1** [comment]
باید روی دکمه یه ایونت کلیک بنویسی و از این متد استفاده کنی
`jalaliDatepicker.show({input});`

**Comment by RmzDav** [comment]
با document.getElementbyId
inputElm

**Comment by RmzDav** [comment]
با document.getElementbyId 
inputElm 

انجام دادم ولی متاسفانه جواب نداد
نمونه مثال هم وجود نداشت
با تشکر

**Comment by majidh1** [comment]
نمونه خدمت شما
https://jsfiddle.net/majidh1/ezxgbts8/19/
