### ISSUE TITLE
مشکل در استفاده در افزونه وردپرسی

### ISSUE THREAD

**Issue by gfxmarket** [majidh1/JalaliDatePicker#27]
سلام 
قصد استفاده از این ابزار در یک افزونه اختصاصی در صفحه ثبت یک فرم را دارم، فایل های JS و CSS به درستی فراخوانی شده منتها کار نمی کند.
داخل فایل html و حتی قالب وردپرس تست کردم جواب میده منتها نمیدونم مشکل کارم کجاست که داخل افزونه روی input مورد نظرم کلیک میکنم هیچ اتفاق خاصی رخ نمی دهد.
تصورم اینه ممکنه تداخل جیکوری باشه یا اینکه script و بایستی در افزونه به گونه ای خاص معرفی کنم.
در ادامه نحوه معرفی script هم قرار میدم ممنون میشم راهنماییم کنید.

`<script type="text/javascript">
jalaliDatepicker.startWatch({
  minDate: "attr",
  maxDate: "attr"
});
</script>`

**Comment by majidh1** [comment]
سلام
لطفا اگه امکانش هست لینک مربوط به صفحه رو ارسال کنید تا بررسی کنم

**Comment by gfxmarket** [comment]
سلام
بابت تاخیر در پاسخگویی عذرمیخوام، متاسفانه هنوز پروژه آنلاین نشده و روی لوکال هاست است.
امروز سعی میکنم روی یک دامنه بالا بیارم و خدمتتون ارایه دهم.
با سپاس فراوان از زحمات و پیگیریتان

**Comment by majidh1** [comment]
دوست عزیز ایشو مدت زیادی باز بوده و مجبورم ایشورو ببندم در صورتی که کمکی از دستم بر میاد در خدمتم
