### ISSUE TITLE
انتخاب زمان

### ISSUE THREAD

**Issue by peyman007** [majidh1/JalaliDatePicker#3]
سلام و درود
اگر انتخاب زمان داشت واقعا فوق العاده میشد
اگر امکانش هست اضافه کنید 
ممنون

**Comment by majidh1** [comment]
سلام
ایشو با نوع New Feature ثبت شد. به زودی این امکان اضافه میشه
ممنون از همکاری شما

**Comment by mojtabafallah13** [comment]
سلام خسته نباشید برای فرمت ب صورت میلادی آپشن نداره؟

**Comment by majidh1** [comment]
> سلام خسته نباشید برای فرمت ب صورت میلادی آپشن نداره؟

منظورتون از به صورت میلادی دقیقا چی هست؟ یه نمونه لطفا بنویسید

**Comment by omidmasoumi** [comment]
با سلام . ممنونم از برنامه عالی فقط تنها مشکل عدم پشتیبانی از زمان میباشد

**Comment by majidh1** [comment]
Doing...

**Comment by iliaghz** [comment]
سلام و درود
کی ورژن 0.7.0 میاد؟

**Comment by majidh1** [comment]
سلام @iliaghz  عزیز 
احتمال زیاد اواسط هفته دیگه منتشر میشه

**Comment by majidh1** [comment]
ورژن 7 با انتخاب زمان افزوده شد این امکان به صورت پیشفرض غیر فعال هست برای فعال نمودن از time:true استفاده کنید
