### ISSUE TITLE
قابلیت انتخاب زمان و مقدار دهی اولیه خودکار

### ISSUE THREAD

**Issue by iliaghz** [majidh1/JalaliDatePicker#31]
اگه راهی داره راهنمایی کنید وگرنه بهش اضافه کنید خیلی این پکیج خوبه حیف اگه اینارو نداشته باشه @majidh1

**Comment by arash88** [comment]
الان این قابلیت auto init موجوده؟ میشه بگین چجوری استفاده میشه؟

**Comment by majidh1** [comment]
کار دیت پیکر بعد از فعال سازی شروع می‌شود. شما اگه لازم دارید تاریخ روز را در input قرار بدین باید value فیلد رو ست کنید و این مورد جزو وظایف یک دیتپیکر نیست.
initDate: مشخص میکنه تاریخ پیشفرض برای نمایش دیتپیکر چی باشه
یعنی اگه فیلد خالی بود در زمان باز شدن دیتپیکر چه تاریخی نمایش داده شود
