### ISSUE TITLE
autoinitialize متد تغییر جداکننده و

### ISSUE THREAD

**Issue by iliaghz** [majidh1/JalaliDatePicker#32]
سلام،
موضوع اول اینکه من میخوام separator بین سال و ماه و روز رو از ``` / ``` به ``` - ``` عوض کنم یعنی ``` 1401/05/06 ``` به ``` 06-05-1401 ``` تغییر بدم.

و موضوع دوم اینکه میخوام وقتی صفحه لود شد یه تاریخی تو خود اینپوت دیتپیکر انتخاب شده باشه ترجیحا تاریخ همون روز باشه. 
راهنمایی!!!

**Comment by majidh1** [comment]
سلام.
برای مورد اول میتونید از کانفیگ زیر استفاده کنید
separatorChars

مثال:
```js
jalaliDatepicker.startWatch({
   separatorChars:{
      date:"-"
   }
}) 
```

مورد دوم چون دیتپیکر قبل از باز شدن امکان مقدار دهی نداره و اگه توسط دیتپیکر انجام بشه ساید افکت زیادی توی پروژه ها ایجاد میکنه  این مورد باید توسط خودتون مقدار دهی بشه

**Comment by iliaghz** [comment]
درباره تم دارک هم یه توضیحی میدید!

**Comment by majidh1** [comment]
برای تم و کلا استایل دیت پیکر باید خودتون تغییرات رو اعمال کنید و کانفیگی وجود نداره
