### ISSUE TITLE
درج تاریخ میلادی در فیلد ثانویه

### ISSUE THREAD

**Issue by mmghaderi** [majidh1/JalaliDatePicker#33]
با سلام
ابزار بسیار زیبا و خوب کار شده، اگر زحمت بکشید و برای انتخاب تاریخ، زمانی که روی تاریخ کلیک می شود، ابزار فیلد ثانویه ای که برایش تعریف می شود را با تاریخ (و زمان) میلادی پر کند. قابلیت بسیار کاربردی است. 
با تشکر از زحمات شما دوست عزیز و آرزوی موفقیت و پیشرفت

**Comment by sorousherafat** [comment]
سلام،
آیا امکان کار روی این ایشو وجود دارد؟

**Comment by majidh1** [comment]
سلام 
با توجه به اینکه دیتپیکر تاریخ جلالی می‌باشد خروجی میلادی و تبدیل تاریخ وظیفه دیتپیکر نیست پیشنهاد میکنم تاریخ رو سمت سرور تبدیل کنید یا برای این مورد خودتون تبدیل رو به سادگی میتونید انجام بدین. نمونه زیر این کار رو انجام میده
https://jsfiddle.net/majidh1/7m4kws2n/19/
