### ISSUE TITLE
انتخاب تاریخ و زمان با دکمه امروز

### ISSUE THREAD

**Issue by iliaghz** [majidh1/JalaliDatePicker#34]
وقتی روی دکمه امروز درون دیتپیکر کلیک شد میخوام زمان و تاریخ همون ساعت و روز رو انتخاب کنه ولی فقط تاریخ رو انتخاب میکنه و زمان رو 0 میزاره!

**Comment by majidh1** [comment]
شما میتونید برای اینکه ساعت 0 تنظیم نشه از initTime استفاده کنید و مقدار پیش فرض زمان را مشخص کنید.
```js
jalaliDatepicker.startWatch({
    initTime: {hour:12,minute:11,second:10},
})
```

در نسخه بعدی با انتخاب امروز زمان لحظه درج میشه
