### ISSUE TITLE
مشخص کردن تمامی تعطیلات رسمی

### ISSUE THREAD

**Issue by amindeist** [majidh1/JalaliDatePicker#37]
سلام 
سپاس بابت کار بسیار زیباتون
چطور میتونم تمامی تعطیلات رسمی را با رنگ قرمز به مانند جمعه ها نمایش بدم؟
من به این شکل عمل میکنم ولی خب یجورایی فقط خط آخر کد رو برای تمام ماهها اعمال میکنه
`            dayRendering: function (dayOptions, input) {
                return {
                    isHollyDay: dayOptions.month === 1 && dayOptions.day <= 4 || dayOptions.day === 13,
                    isHollyDay: dayOptions.month === 2 && dayOptions.day === 3 || dayOptions.day === 13 || dayOptions.day === 14,
                    isHollyDay: dayOptions.month === 3 && dayOptions.day === 14 || dayOptions.day === 15,
                    isHollyDay: dayOptions.month === 4 && dayOptions.day === 19 || dayOptions.day === 27,
                    isHollyDay: dayOptions.month === 5 && dayOptions.day === 16 || dayOptions.day === 17,
                    isHollyDay: dayOptions.month === 6 && dayOptions.day === 26,
                    isHollyDay: dayOptions.month === 7 && dayOptions.day === 3 || dayOptions.day === 5 || dayOptions.day === 13,
                }
            },`

**Comment by majidh1** [comment]
سلام 
ممنون از همکاریتون 
مشکل کد اینه که چندین مرتبه isHollyDay مقداردهی شده بنابرین آخرین مقداردهی معتبر هست.
