### ISSUE TITLE
مشکل در انتخاب زمان

### ISSUE THREAD

**Issue by novinceram** [majidh1/JalaliDatePicker#38]
سلام در زمانی که از فیلد زمان در modal استفاده میکنم لیست انتخاب ساعت و دقیقه بعد کلیل نمایش داده میشه و بلافاصله بسته میشه
.ولی اگر در صفحه اصلی استفاده بکنم این مشکل وجود نداره

**Comment by majidh1** [comment]
سلام
لطفا نمونه کدی ارسال کنید تا بررسی کنم.
اگه در modal استفاده میکنید باید zIndex دیتپیکر بالاتر از modal باشه
`jalaliDatepicker.startWatch({zIndex:10000});`

**Comment by alirezamosleh** [comment]
سلام بله
مشکل باز نشدن data picker مربوط به zIndex هست
ولی باز نشدن دراپ دون مربوط به container میشه...باید کانتینر ایجاد دیتا پیکر رو به داخل modal جابه جا کنیم
درواقع اگر مقدار زیر رو ست کنیم مشکل حل میشه
container:'.modal'
یا کلاسی مشابه این که دیتا رو داخل modal ببره

**Comment by mr-miladkarimi** [comment]
سلام
مشکل باز نشدن data picker مربوط به z-index هست
ولی راه حل باز نشدن dropdown داخل modal برای این هست که برای modal مقدار aria-hidden="true" فراخوانی نشده است

```
 <div class="modal" id="test" tabindex="-1" aria-modal="true" role="dialog" aria-hidden="true">
      <div class="modal-dialog modal-lg}">
          <div class="modal-content">
                ...
          </div
      </div>
 </div>
```

**Comment by majidh1** [comment]
ممنون از راهنمایی عالی @mr-miladkarimi
