### ISSUE TITLE
استفاده در پروژه های React

### ISSUE THREAD

**Issue by AbolfazlHeidarpour** [majidh1/JalaliDatePicker#4]
با سلام و وقت بخیر خدمت شما.
چطور می توانیم تقویم جلالی را در پروژه های ریکت جی اس، استفاده کنیم.؟
برای مثال چطور
import کنیم؟

**Comment by majidh1** [comment]
سلام وقت بخیر
چون ماژول اصلی خروجی نداره در حال حاظر امکان ایمپورت مستقیم نداره ولی میتونی از window.jalaliDatepicker استفاده کنی
