### ISSUE TITLE
محدود کردن ساعت

### ISSUE THREAD

**Issue by mmo1383** [majidh1/JalaliDatePicker#42]
سلام
چگونه وقتی تنها ساعت را نمایش می دهد، بگوییم فقط از ساعت مثلا 9 تا 12 را نمایش دهد

**Comment by majidh1** [comment]
سلام
دیت پیکر برای محدود کردن زمان در نسخه فعلی (8.6) تنظیمات نداره و این امکان فقط برای تاریخ امکان پذیر هست.

**Comment by mmo1383** [comment]
خوب باید چی رو عوض کنم که بشود؟

**Comment by majidh1** [comment]
> خوب باید چی رو عوض کنم که بشود؟

با توجه به اینکه عرض کردم تنظیماتی وجود نداره متوجه منظورتون از اینکه چی رو باید عوض کنم نشدم. توی سورس دیت پیکر میخواهید تغییر بدین؟

**Comment by mmo1383** [comment]
بله
به صورت اسکریپت داخل صفحه بیاورم و فقط ساعت ها را خودم بدم

**Comment by sohrabi2050** [comment]
@mmo1383 عزیز،
این کتابخانه این امکان که شما بتوانید بازه زمانی ای برای ساعت آن در نظر بگیرید را ندارد.
در صورتی که تمایل داشته باشید میتونی خودتون روی این سورس که باز است تغییرات لازم رو اعمال کنید که بتونین از چنین امکانی بهره‌مند بشید.
اما در حال حاضر این امکان در این دیت‌پیکر وجود ندارد.

**Comment by mmo1383** [comment]
بله فهمیدم
فقط کدام قسمت ساعت ها نوشته شده که تغییر دهم
