### ISSUE TITLE
مشکل نمایش

### ISSUE THREAD

**Issue by boobProgrammer** [majidh1/JalaliDatePicker#5]
سلام

زمانی که ازتفاع صفحه ای که درون اون داریم دیت پیکر را استفاده میکنیم زیاد باشه و یکم اسکرول کنیم پس از کلیک داخل input دیت پیکر یک لحظه میاد و میره . اگر میلیمتری سمت چپ یا راست اینپوت کلیک کنیم نمایش داده میشه

منظورم اینه که دیت پیکر در هر شرایطی زیر اینپوت باید باز بشه ولی بعضی مواقع روی اینپوت باز میشه و این باعث میشه که در لحظه بسته بشه

**Comment by majidh1** [comment]
سلام 
بررسی کردم مشکل توی نسخه جدید حل شد. (v0.2.7)
