### ISSUE TITLE
updating package-lock.json

### ISSUE THREAD

**Issue by sorousherafat** [majidh1/JalaliDatePicker#50]
با سلام و خسته نباشید،

![image](https://user-images.githubusercontent.com/71870584/209584830-5d20dd9f-87ca-4280-87d3-034604f0b9aa.png)

طبق تصویر بالا، گویا که فایل `package-lock.json` با یک نسخه قدیمی npm نوشته شده است و هر کاربری که قصد بیلد پکیج از سورس‌کد را داشته باشد با این warning و انتظار بعد از آن روبه‌رو می‌شود.

پیشنهاد من، آپدیت فایل `package-lock.json` است. درصورت تایید و راهنمایی، شخصا نیز علاقه‌مند به انجام این کار هستم.

اطلاعات مربوط‌به ورژن:

```
$ node -v
v18.0.0

$ npm -v
9.1.2
```

**Comment by majidh1** [comment]
سلام سلامت باشید
نادیده بگیرید. این فقط یک هشدار است و روی نصب ماژول‌ها تأثیری ندارد.
در صورت آپدیت فایل با نسخه بالاتر نسخ پایینتر به مشکل میخورن با توجه به پکیج‌های این کتابخانه ورژن npm مناسب انتخاب شده است
