### ISSUE TITLE
خطا در event دکمه خالی کردن

### ISSUE THREAD

**Issue by BluestarCo** [majidh1/JalaliDatePicker#52]
با سلام

دکمه خالی هیچ گونه event ارسال نمیکنه تا متوجه تغیرات توی input شیم لطفا موقع خالی کردن input یا change بفرستید

**Comment by majidh1** [comment]
سلام با تشکر از همکاری شما
توی نسخه 0.9.2 اصلاح شده است و event مربوط به تغییرات صدا زده میشه
jdp:change
