### ISSUE TITLE
نحوه تنظیم تاریخ انتخاب شده

### ISSUE THREAD

**Issue by ahmadrezadev** [majidh1/JalaliDatePicker#55]
سلام وقت بخیر
نحوه تنظیم تاریخ پیش فرض به هنگام Load صفحه (از مقدار value خود input بخونه) یا جایی دیگه بهش دارد به چه صورت عمل میکنه؟
من با initDate هم به صورت میلادی و شمسی به صورت option در  jalaliDatepicker.startWatch قرار دادم نشد و مقدار پیش فرض رو نمایش نداد.
ممنون میشم راهنمایی کنید.

        jalaliDatepicker.startWatch({
            initDate: new Date("2015-03-25"),
        });

        jalaliDatepicker.startWatch({
            initDate: "2015/03/25"
        });

        jalaliDatepicker.startWatch({
            initDate: "1379/03/02"
        });

**Comment by majidh1** [comment]
سلام وقت بخیر
initDate تاریخ پیشفرض برای دیتپیکر هست در حقیقت با این تاریخ دیت‌پیکر باز می‌شود به روش زیر تنظیم میشود
{ initDate: {year:1400,month:1,day:5} }

تکراری https://github.com/majidh1/JalaliDatePicker/discussions/48
