### ISSUE TITLE
نحوه استفاده

### ISSUE THREAD

**Issue by lifebyweb** [majidh1/JalaliDatePicker#58]
آقا مجید خیلی ممنون از این کدهای با صفاتون
بی زحمت چندتا مثال هم بزنید عالی میشه
البته من از اون فایل test اطلاعات رو تونستم تا حدودی متوجه بشم
ولی برای استفاده بهتر ممنون میشم یه چندتا نمونه مثل همون نمونه روزهای عید
اضافه کنید.
با تشکر

**Comment by majidh1** [comment]
سلام وقت بخیر ممنون از شما که به توسعه فرهنگ اوپن سورس کمک میکنید لینک زیر مجموعه‌ای از نمونه‌های ایجاد شده به همراه توضیحات هست
https://codepen.io/collection/wajWMo
