### ISSUE TITLE
نحوه استفاده از قالب ها تقویم

### ISSUE THREAD

**Issue by download69** [majidh1/JalaliDatePicker#6]
وقت بخیر
یکسری تصویر از تقویم شما در صفحه معرفی استفاده کرده اید، برای استفاده از قالب ها باید دستی خودمون فایل css رو تغییر بدیم یا اینکهمی‌شه از آپشن ها استفاده کرد؟

**Comment by majidh1** [comment]
سلام
شما میتوانید از دو پارامتر 
plusHtml و minusHtml
 جهت تغییر ایکون ها استفاده کنید

و برای تغییرات ui میتوانید از css استفاده کنید
به دلیل ثابت بودن کلاس های دیتپیکر استفاده از css بدون مشکل هست

اینم نمونه که یکی از دوستان استفاده کرده در پروژه خودش:
<img src="/majidh1/JalaliDatePicker/raw/main/res/sample5.png" width="32%" style="max-width:100%;">
jdp-container {
    background: #323232;
}

jdp-container .jdp-months, jdp-container .jdp-years {
    color: rgb(255 255 255 / 80%);
    fill: rgb(255 255 255 / 80%);
}
jdp-container .jdp-day-name {
    background-color: rgb(255 255 255 / 10%);
}
jdp-container .jdp-day, jdp-container .jdp-day-name {
    color: rgb(255 255 255 / 80%);
}
jdp-container .jdp-day:empty {
    border-color: #323232;
}
jdp-container .jdp-btn-empty, jdp-container .jdp-btn-today {
    background: #1d497e;
}

**Comment by Absalamyar** [comment]
اینجا هدف شمارا درست نفهمیدم از plusHtml و minusHtml که چطوری کار میکند چون کود css بالایی را کاپی کردم اصلا کار نکرد فکر کنم کود css  دوباره داخل دیت پیکر هم تنظیم میگردد میشه یک مثال کامل ارایه بدارید لطفآ هم input باشد هم css و اسکریپت دیت بیکر تا ببینم چطوری css تنظیم میگردد

**Comment by mordadam** [comment]
> سلام شما میتوانید از دو پارامتر plusHtml و minusHtml جهت تغییر ایکون ها استفاده کنید
> 
> و برای تغییرات یو آی میتوانید از سی اس اس استفاده کنید به دلیل ثابت بودن کلاس های دیتپیکر استفاده از سی اس اس بدون مشکل هست
> 
> اینم نمونه که یکی از دوستان استفاده کرده در پروژه خودش: <img alt="" width="32%" src="/majidh1/JalaliDatePicker/raw/main/res/sample5.png">
> 
> ```css
> jdp-container,jdp-container .jdp-year select,jdp-container .jdp-month select{
>     background: #323232;
> }
> 
> jdp-container .jdp-months, jdp-container .jdp-years {
>     color: rgb(255 255 255 / 80%);
>     fill: rgb(255 255 255 / 80%);
> }
> jdp-container .jdp-day-name {
>     background-color: rgb(255 255 255 / 10%);
> }
> jdp-container .jdp-day, jdp-container .jdp-day-name {
>     color: rgb(255 255 255 / 80%);
> }
> jdp-container .jdp-day:empty {
>     border-color: #323232;
> }
> jdp-container .jdp-btn-empty, jdp-container .jdp-btn-today, jdp-container .jdp-days .jdp-day.selected {
>     background: #1d497e !important;
> }
> ```

کاش میشد تنها با یک تنظیم ساده مثل (theme: "dark") این کار برامون انجام میشد و یا برعکس ...
