### ISSUE TITLE
بدست آوردن مقدار today

### ISSUE THREAD

**Issue by mahdi-Abdolhosseini** [majidh1/JalaliDatePicker#60]
سلام وقت بخیر. میخواستم بدونم چطور میتونم maxDate رو قبل از باز شدن تقویم تغییر بدم مثلا تا 6 ماه بعد از today.متغیر today رو میشه ازش استفاده کرد و مثلا today.getMoth  و today.setMoth  کرد؟

**Comment by majidh1** [comment]
سلام وقت بخیر میتونید به دو روش محدود کنید
1- استفاده از اتریبیوت: (برای استفاده از اتریبیوت باید مقدار maxDate برابر با attr باشه)
data-jdp-max-date="1402/10/08"
لینک نمونه: https://codepen.io/majidh1/pen/qBRQBzd
2- استفاده از maxDate به صورت آبجکت
{
maxDate: {year:1402,month:10,day:8}
}

**Comment by mahdi-Abdolhosseini** [comment]
ممنون از پاسخ ولی منظورم استفاده از متغیر جاوا اسکریپت today هست که تقویم شما بدست میاره و مثلا برای نمایش دکمه امروز ازش استفاده میکنید
