### ISSUE TITLE
مشکل در autoHide

### ISSUE THREAD

**Issue by MrSidou** [majidh1/JalaliDatePicker#62]
عملکرد autoHide به درستی انجام نمیشد، پس از مقداردهی مستقیم با مقدار True این مشکل رفع شد. به گمانم مقدار پیش فرض false تعریف شده است.

**Comment by majidh1** [comment]
سلام لطفا توضیح بیشتری بدین عملکرد autoHide به این شکل هست که با کلیک روی خارج از دیت پیکر و یا انتخاب تاریخ دیتپیکر به صورت اتوماتیک بسته شود

**Comment by majidh1** [comment]
به دلیل عدم پاسخگویی ایشو بسته شد
