### ISSUE TITLE
چطور برای input های مختلف شخصی سازی کنیم؟

### ISSUE THREAD

**Issue by xorenir** [majidh1/JalaliDatePicker#63]
سلام، من میخوام برای input های  مختلفی استفاده کنم ولی خب وقتی از startWatch استفاده میکنم نمیشه.

مثلا:
//برای فرم معمولی
```
jalaliDatepicker.startWatch({

    minDate: 'attr',
    maxDate: 'attr',
    container: 'body'
});
```

// برای مودال
```
jalaliDatepicker.startWatch( {
    zIndex: 1055,
    minDate: "attr",
    maxDate: "attr",
    container: "body .modal.show",
    selector: '.modal input[data-jdp]'
});
```

یا مثلا تم های مختلف برای input های مختلف ؟

**Comment by sortheme** [comment]
> سلام ممنون از همکاریتون روی پروژه این پکیج فعلا امکان اینیت چندباره را ندارد پیشنهاد میکنم برای مودال فقط zIndex ست کنید تو تست‌های پکیج با ست کردن zIndex مشکلات مودال حل میشد و نیازی به کانتینر نبود سعی میکنم در نسخه‌های بعدی امکان اینیت مجزا هر اینپوت رو اضافه کنم

سلام برای چند اینپوت اقدامی نکردید؟ خیلی لازمه
