### ISSUE TITLE
امکان دیسیبل کردن انتخاب برخی تاریخ ها

### ISSUE THREAD

**Issue by MeysamSabeti** [majidh1/JalaliDatePicker#66]
سلام وقتتون بخیر.ممنون بابت ساخت چنین پکیج فوق العاده ای ، میخواستم بپرسم امکان دیسیبل کردن برخی روزها وجود نداره؟؟
مثلا تنظیمات رو جوری اعمال کنیم که توی ماه فروردین ، برخی روز ها رو کاربر نتونه انتخاب کنه

**Comment by majidh1** [comment]
سلام ممنون از مشارکت شما به وسیله متد dayRendering میتونید روی تمامی روز‌های نمایش داده شده کنترل داشته باشید
```javascipt
jalaliDatepicker.startWatch({
  dayRendering: function(day){
    return {
     isHollyDay: day.month == 1 && day.day <= 4,
     isValid = false // امکان غیر فعال کردن روز
    }
  }
})
```

**Comment by MeysamSabeti** [comment]
سپاس از راهنماییتون .
و اگه در یک صفحه چندتا اینپوت تاریخ باشه ، چطور میشه برای هر اینپوت به صورت جداگانه مقادیری رو دیسیبل کرد؟؟؟

**Comment by majidh1** [comment]
خواهش میکنم
پارامتر ورودی دوم این متد به شما اینپوت را پاس میدهد و میتوانید روی اینپوت‌ها تنظیمات دلخواه خودتون رو داشته باشید
مثال:

```html
<input type=text data-jdp />

<input type=text data-jdp data-jdp-only-valid-day placeholder="only-valid-day"/> 
```

```javascript
jalaliDatepicker.startWatch({
  dayRendering: function(day, input){
    if(!input.hasAttribute("data-jdp-only-valid-day")) return {}; //data-jdp-only-valid-day فقط یک نام نمونه است هر نامی میتواند باشد
    var isHollyDay = day.month == 1 && day.day <= 15;
    return {
     isHollyDay: isHollyDay,
     isValid: !isHollyDay // امکان غیر فعال کردن روز
    }
  }
}) 
```

**Comment by MeysamSabeti** [comment]
سپاس بیکران
