### ISSUE TITLE
چطور میشه ساعت هم انتخاب کرد ؟ 

### ISSUE THREAD

**Issue by vahidalvandi** [majidh1/JalaliDatePicker#68]
سلام ممنون بابت ساخت پلاگین خیلی خوب [JalaliDatePicker](https://github.com/majidh1/JalaliDatePicker) یک سوال دارم که آیا میشه در کنار انتخاب تاریخ ساعت و دقیقه هم انتخاب کرد ؟

**Comment by majidh1** [comment]
سلام وقت بخیر
ممنون بابت مشارکت شما 
بله این امکان وجود دارد
میتونید از لینک استفاده کنید و نمونه‌های مربوط به زمان و تاریخ را مشاهده کنید
https://codepen.io/majidh1/pen/dyqrmXW
