### ISSUE TITLE
امکان غیرفعالسازی تایپ دستی توسط کاربر

### ISSUE THREAD

**Issue by hosseinghanbarpor** [majidh1/JalaliDatePicker#73]
ممنون بابت پکیچ خوبتون.
به نظرم خوب میشه اگه در تنظیمات امکان غیرفعالسازی تایپ دستی توسط کاربر رو اضافه کنیم.
در بسیاری از موارد که می خوایم سمت سرور تبدیل تاریخ رو انجام بدیم.انتظار یک فرمت استاندارد جلالی رو داریم که بتونیم تبدیل اش به میلادی کنیم.ولی ممکنه کاربر به صورت دستی یک متن نامرتبط در باکس تقویم مدنظر وارد کنه و کل فرآيند تبدیل و ثبت تاریخ در سمت سرور رو دچار اختلال می کند.مثلا یک متغییر به نام onlySelectByPicker که وقتی true قرارداده شد.کاربر نتونه دستی چیزی وارد کند و فقط باید از datepicker انتخاب کنه.

**Comment by majidh1** [comment]
سلام وقتتون بخیر
این امکان وجود دارد
با استفاده از کانفیگ autoReadOnlyInput میتونید این کار رو انجام بدین

**Comment by hosseinghanbarpor** [comment]
سپاس از راهنماییتون
