### ISSUE TITLE
پاک نشدن تقویم

### ISSUE THREAD

**Issue by JAAVAAD** [majidh1/JalaliDatePicker#77]
سلام چرا وقتی تاریخ و زمان همزمان فعال هستند پس از انتخاب تاریخ تقویم همچنان روی صفحه میمونه و پاک نمیشه؟
![Uploading Screenshot 2023-11-12 111458.jpg…]()

**Comment by majidh1** [comment]
سلام
برای اینکه به کاربر اجازه بدیم تایم هم انتخاب کنه باز میمونه اگر بسته بشه کاربر برای انتخاب تایم مجبوره دوباره باز کنه دیتپیکر رو

**Comment by JAAVAAD** [comment]
ممنون
منطقی هست اگر خلافشو جایی دیدم حتما بهتون اطلاع مید.
اما میتونید 👇 مثال پاین رو استفاده کنید. 
مثلا با انتخاب زمان( پیشفرض زمان فعلی باشه) تقویم بسته نشود ولی با انتخاب تاریخ بسته شود. اینو اضافه کنید به نظر من منطقی هست

**Comment by jafarpalidehsheibak** [comment]
سلام .موقعی که میخوام دیت پیکر رو توی modal نشون بدم ، میفته زیرش . 
چطور میتونم بیارمش توی خود modal ؟
