### ISSUE TITLE
فعال بودن روز خاص

### ISSUE THREAD

**Issue by hasssan1373** [majidh1/JalaliDatePicker#78]
سلام امکان این وجود داره که روز های خاصی فعال فعال باشد؟ مثلا ورودی با فرمت زیر بهش بدیم.
 enableDates: ["1042-09-22", "1402-09-23", "1402-09-26", "1402-09-27", "1402-09-30"],

**Comment by majidh1** [comment]
سلام وقت بخیر ایشو زیر را مشاهده کنید
https://github.com/majidh1/JalaliDatePicker/issues/66

**Comment by hasssan1373** [comment]
یعنی من برای فعال بودن ده روز بیام 355 روز رو به صورت دستی غیر فعال کنم؟! این منطقی هست؟
تازه بازم کامل نمیشه انجام دادم
من میخوام ورودی روز های فعال رو بهش بدم و فقط اون روزها قابل انتخاب باشه

**Comment by majidh1** [comment]
این متد کمک میکنه تا هر محدودیتی لازم دارید بزارید.
حالا اگه محدودیت به این شکله که میخوای فقط **از تاریخ** خاص **تا تاریخ** خاص رو فعال کنید میتونید از دو کانفیگ زیر استفاده کنید
نمونه: https://jsfiddle.net/dws2vf1j/
jalaliDatepicker.startWatch({
	minDate: {
		year: 1402,
		month: 9,
		day: 22
	},
	maxDate: {
		year: 1402,
		month: 9,
		day: 30
	}
});

اگه این کانفیگ‌ها به ازای هر اینپوت متفاوت هست میتونید از دو اتریبیوت زیر روی اینپوت‌ها استفاده کنید.
نمونه: https://jsfiddle.net/0yeu2f9s/
data-jdp-min-date
data-jdp-max-date

jalaliDatepicker.startWatch({
	minDate: "attr",
	maxDate: "attr"
});

**Comment by hasssan1373** [comment]
نه دوست عزیز این متد کارای نداره چون ممکن چند روز بین این روزها بخوام غیر فعال باشه 
همین طور که تو پیام اول گفتم من یه متد فعال بود روز خاص میخوام که روزها رو خودم بهش بدم

مثال : enableDates: ["1042-09-22"، "1402-09-23"، "1402-09-26"، "1402-09-27"، "1402-09-30"]

**Comment by majidh1** [comment]
شما نمونه‌ی ارسال شده رو دیدین! لطف میکنی بگی چرا این نمونه نیازتون رو بر طرف نکرده؟
نمونه: https://jsfiddle.net/c9t4m60p/
