### ISSUE TITLE
نشان دادن دیت پیکر در مودال

### ISSUE THREAD

**Issue by jafarpalidehsheibak** [majidh1/JalaliDatePicker#79]
سلام .موقعی که میخوام دیت پیکر رو توی modal نشون بدم ، میفته زیرش .
چطور میتونم بیارمش توی خود modal ؟

**Comment by majidh1** [comment]
سلام شما باید توی کانفیگ دیت پیکر zIndex رو بیشتر کنید تا مشکل برطرف بشه

**Comment by jafarpalidehsheibak** [comment]
تنظیمات اشتباه ؟

**Comment by jafarpalidehsheibak** [comment]
خیلی ممنون . عالی بود . درست شد .
