### ISSUE TITLE
امکان انتخاب چند تاریخ و یا رنج تاریخ

### ISSUE THREAD

**Issue by mohammadZx** [majidh1/JalaliDatePicker#81]
سلام آیا امکان انتخاب چند تاریخ رو داره؟!
آیا امکان انتخاب یک بازه زمانی رو داریم؟!
اگر اینطوره راهنماییم کنید.

**Comment by MohammadZarifiyan** [comment]
سلام من هم چنین مشکلی رو دارم.

**Comment by majidh1** [comment]
سلام وقت بخیر این امکان به صورت داخلی در دیتپیکر وجود ندارد اما معمولا به روش زیر در سامانه ها استفاده شده است
https://codepen.io/majidh1/pen/LYapVoX

**Comment by MohammadZarifiyan** [comment]
> سلام وقت بخیر این امکان به صورت داخلی در دیتپیکر وجود ندارد اما معمولا به روش زیر در سامانه ها استفاده شده است https://codepen.io/majidh1/pen/LYapVoX

بله ولی اگر اضافه بشه خیلی پکیج دوست داشتنی تری میشه. مطمئنم خیلی ها از اضافه شدن چنین قابلیتی خوشحال خواهند شد.
