### ISSUE TITLE
Feature Request: Customize Month Names for Afghan Calendar

### ISSUE THREAD

**Issue by SabawoonDaqiq8** [majidh1/JalaliDatePicker#83]
I need to customize the month names to reflect the Afghan calendar instead of the default Iranian names. Could you consider adding a feature in jb-date-input for users to set custom month names?

**Comment by majidh1** [comment]
Hi, yes, the names of the months can be changed 
you can use the two configs below.

months & days

Sample:
```javascript
jalaliDatepicker.startWatch({
months:	["فروردین", "اردیبهشت", "خرداد", "تیر", "مرداد", "شهریور", "مهر", "آبان", "آذر", "دی", "بهمن", "اسفند"]
})
```

**Comment by SabawoonDaqiq8** [comment]
I appreciate that, and is it possible to get the day numbers converted to English?
