### ISSUE TITLE
نمایش تاریخ امروز در input و تغیر theme دیت پیگر

### ISSUE THREAD

**Issue by Absalamyar** [majidh1/JalaliDatePicker#85]
سلام دوست عزیز 
چطوری میشه تاریخ امروز را در input نمایش بدهم بصورت پیش فرض و همچنان چطوری theme دیت پیگر را تغیر بدهم و یا با استفاده از css چطوری تغیر ایجاد نمایم لطفا کمک نماید
با احترام

**Comment by majidh1** [comment]
سلام وقت بخیر این موارد قبلا مطرح شده از دو لینک زیر میتونید استفاده کنید
https://github.com/majidh1/JalaliDatePicker/issues/6
https://github.com/majidh1/JalaliDatePicker/discussions/67
