### ISSUE TITLE
تنظیم نمودن سایز دیت بیگر و قیمت گذاری با استفاده از فارم

### ISSUE THREAD

**Issue by Absalamyar** [majidh1/JalaliDatePicker#86]
دوست عزیز من برایتان یک اسکرین شارت میفرستیم ببینیت با استفاده از زبان PHP معلومات را جستجو میکتم و هر زمان که form ما با استفاده از میتود POST دیتا را جستجو میکند قیمت های که داخل input انتخاب میگردد نمایش میدهد اما زمانیکه تازه وارد صحفه میشویم باید تاریخ روز را نمایش بدهد با استفاده از رویش قبلی که از شما پرسیدم جواب نداد چون وقتی فارم submit میشود تاریخ انتخاب شده را به تاریخ امروز تبدیل میکند میشه اینجا رهنمای نماید
<input data-jdp id="start_date" name="start_date" class="form-control" value="<?= isset($_POST['start_date']) ? $_POST['start_date'] : ''; ?>" placeholder="انتخاب تاریخ شروع">
این هم انپوت من است میخواهم هر زمان که انپوت submit میشود این قیمت ها را نمایش بدهد در غیر آن تاریخ امروز را نمایش
و همچنان چطوری میتوانیم سایز دیت پیکر را برابر با سایز انپوت نمایم . لطفآ اینجا رهنمای بکنید
![datepicker](https://github.com/majidh1/JalaliDatePicker/assets/115398798/82c03632-e6f5-4048-b0c6-c1530186a4b4)

**Comment by Absalamyar** [comment]
<input data-jdp id="start_date" name="start_date" class="form-control" value="<?= isset($_POST['start_date']) ? $_POST['start_date'] : ''; ?>" placeholder="انتخاب تاریخ شروع"> 
 این کد انپوت است

**Comment by majidh1** [comment]
سلام وقت بخیر دوست عزیز اینکه فرم در زمان لود شدن مقدار پیشفرض داشته باشد از وضایف دیت پیکر نیست و باید خودتان مدیریتش کنید که هم از فرانت و هم سمت بک‌اند قابل پیاده سازی هست

نمونه php با استفاده از پکیج https://github.com/morilog/jalali

<input value="<?Jalalian::forge('today')->format('%Y/%m/%d')?>" data-jdp/>

البته من php دولوپر نیستم و شماتیک نوشتم

**Comment by majidh1** [comment]
.jdp-container{
    max-width: yourInputSize;
    min-width: yourInputSize;
}
