### ISSUE TITLE
رویداد OnChange کار نمی کند

### ISSUE THREAD

**Issue by zanganli** [majidh1/JalaliDatePicker#9]
سلام دوست عزیز . چگونه تغییر مقدار اینپوت را رصد کنیم؟
رویداد onChange کار نمی کند
با change جی گوئری هم تریگر نشد.
لطفا راهنمایی کنید با تشکر

**Comment by majidh1** [comment]
سلام، نمونه کد زیر بدون مشکل کار میکنه
```
<input type="text" data-jdp id="change_sample">
document.getElementById('change_sample').addEventListener('change', (event) => {
  console.log(event)
});
```
