### ISSUE TITLE
انتخاب سال و ماه اینده

### ISSUE THREAD

**Issue by zahedi-dev** [majidh1/JalaliDatePicker#92]
سلام؛ وقت بخیر.
خیلی ممنون بابت این پروژه خفن.
ما الان اسفند هستیم و تنظیم شده که تا از تاریخ جاری انتخاب بتونیم حالا سال رو اگر عوض کنیم و بعدی بریم ماه نمیاد روی فروردین و روی اسفند سال قبلی باقی میمونه. یا اینکه اگر دکمه پلاس ماه رو بزنیم چرا نمیره سال اینده؟ راه حلی دارید؟
ممنون.

**Comment by majidh1** [comment]
سلام ممنون از شما بله میتوانید از کانفیگ changeMonthRotateYear استفاده کنید در صورتی که مقدار آن را true ست کنید با تغییر ماه سال نیز کم یا زیاد می‌شود
