### ISSUE TITLE
نمایش ندادن value

### ISSUE THREAD

**Issue by mostafahn** [majidh1/JalaliDatePicker#96]
سلام
وقتی از datepicker استفاده میکنم و تاریخ انتخاب میکنم تاریخ انتخاب شده نمایش میده ولی در قسمت value در inspect element خالیه

**Comment by majidh1** [comment]
در inspect برای input ها attribute ست نمیشه کلا این مربوط به دیت پیکر نیست آیا نکته دیگه ای هست؟
