### ISSUE TITLE
چگونه میتوانی z-index را تغیر بدهیم؟ 

### ISSUE THREAD

**Issue by saboorbahawi** [majidh1/JalaliDatePicker#98]
چگونه میتوانیم z-index را از حالت 1000 تغیر بدهیم؟

زیرا در هنگام استفاده با Bootstrap modal انتخاب کننده تاریخ به عقب پنهان میگردد.

**Comment by majidh1** [comment]
تکرار ایشو
https://github.com/majidh1/JalaliDatePicker/issues/79#issuecomment-1836068063
